export type ColorType = 'title'
  | 'defaultLight'
  | 'defaultDark'
  | 'highLight'
  | 'highDark'
  | 'grey5'
  | 'grey6'
  | 'grey10'
  | 'grey15'
  | 'grey20'
  | 'primary10'
  | 'primary20'
  | 'primary50'
  | 'primary100'
  | 'primaryRed'
  | 'success'
  | 'warning'
  | 'toastBackground'